<?php /* Smarty version 2.6.18, created on 2012-05-30 18:07:44
         compiled from Site/renew.html */

$this->_cache_serials['/home/hm1002/GM/gm/link/APP/View/View_c/%%1C^1C2^1C2840BE%%renew.html.inc'] = 'eded25321b75d9342e743131d706b27d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', '_t', 'Site/renew.html', 9, false),array('function', 'url', 'Site/renew.html', 12, false),array('modifier', 'date_format', 'Site/renew.html', 58, false),)), $this); ?>
<?php
function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_0(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'prevPage'), $_smarty);
}


function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_1(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'renew'), $_smarty);
}


function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_2(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'renew','page' => $_smarty->_tpl_vars['pager_data']['prevPage']), $_smarty);
}


function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_3(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'prevPage'), $_smarty);
}


function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_4(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'renew'), $_smarty);
}


function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_5(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'renew','page' => $_smarty->_tpl_vars['pages'][$_smarty->_sections['page']['index']]['number']), $_smarty);
}


function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_6(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'nextPage'), $_smarty);
}


function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_7(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'renew','page' => $_smarty->_tpl_vars['pager_data']['nextPage']), $_smarty);
}


function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_8(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'nextPage'), $_smarty);
}


function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_9(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'update_date'), $_smarty);
}


function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_10(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'editsite','id' => $_smarty->_tpl_vars['sites'][$_smarty->_sections['list']['index']]['id']), $_smarty);
}


function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_11(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'edit_or_delete'), $_smarty);
}


function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_12(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'mailadmin','id' => $_smarty->_tpl_vars['sites'][$_smarty->_sections['list']['index']]['id']), $_smarty);
}


function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_13(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'mail_to_admin'), $_smarty);
}


function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_14(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'prevPage'), $_smarty);
}


function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_15(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'renew'), $_smarty);
}


function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_16(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'renew','page' => $_smarty->_tpl_vars['pager_data']['prevPage']), $_smarty);
}


function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_17(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'prevPage'), $_smarty);
}


function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_18(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'renew'), $_smarty);
}


function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_19(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'renew','page' => $_smarty->_tpl_vars['pages'][$_smarty->_sections['page']['index']]['number']), $_smarty);
}


function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_20(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'nextPage'), $_smarty);
}


function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_21(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'renew','page' => $_smarty->_tpl_vars['pager_data']['nextPage']), $_smarty);
}


function _smarty_tplfunc_eded25321b75d9342e743131d706b27d_22(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'nextPage'), $_smarty);
}



?>
