<?php /* Smarty version 2.6.18, created on 2012-05-30 18:07:55
         compiled from Site/recommend.html */

$this->_cache_serials['/home/hm1002/GM/gm/link/APP/View/View_c/%%2A^2A1^2A164550%%recommend.html.inc'] = '1837c1368ae5b47e8c20fbb82b66be74';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', '_t', 'Site/recommend.html', 10, false),array('function', 'url', 'Site/recommend.html', 13, false),array('modifier', 'date_format', 'Site/recommend.html', 60, false),)), $this); ?>
<?php
function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_0(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'prevPage'), $_smarty);
}


function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_1(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'recommend'), $_smarty);
}


function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_2(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'recommend','page' => $_smarty->_tpl_vars['pager_data']['prevPage']), $_smarty);
}


function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_3(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'prevPage'), $_smarty);
}


function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_4(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'recommend'), $_smarty);
}


function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_5(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'recommend','page' => $_smarty->_tpl_vars['pages'][$_smarty->_sections['page']['index']]['number']), $_smarty);
}


function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_6(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'nextPage'), $_smarty);
}


function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_7(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'recommend','page' => $_smarty->_tpl_vars['pager_data']['nextPage']), $_smarty);
}


function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_8(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'nextPage'), $_smarty);
}


function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_9(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'update_date'), $_smarty);
}


function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_10(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'editsite','id' => $_smarty->_tpl_vars['sites'][$_smarty->_sections['list']['index']]['id']), $_smarty);
}


function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_11(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'edit_or_delete'), $_smarty);
}


function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_12(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'mailadmin','id' => $_smarty->_tpl_vars['sites'][$_smarty->_sections['list']['index']]['id']), $_smarty);
}


function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_13(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'mail_to_admin'), $_smarty);
}


function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_14(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'prevPage'), $_smarty);
}


function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_15(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'recommend'), $_smarty);
}


function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_16(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'recommend','page' => $_smarty->_tpl_vars['pager_data']['prevPage']), $_smarty);
}


function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_17(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'prevPage'), $_smarty);
}


function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_18(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'recommend'), $_smarty);
}


function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_19(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'recommend','page' => $_smarty->_tpl_vars['pages'][$_smarty->_sections['page']['index']]['number']), $_smarty);
}


function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_20(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'nextPage'), $_smarty);
}


function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_21(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'recommend','page' => $_smarty->_tpl_vars['pager_data']['nextPage']), $_smarty);
}


function _smarty_tplfunc_1837c1368ae5b47e8c20fbb82b66be74_22(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'nextPage'), $_smarty);
}



?>
