<?php /* Smarty version 2.6.18, created on 2012-05-30 18:07:50
         compiled from Site/new.html */

$this->_cache_serials['/home/hm1002/GM/gm/link/APP/View/View_c/%%67^67B^67B6B2BD%%new.html.inc'] = '66983347496cdbdff87ec8c352460f88';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', '_t', 'Site/new.html', 10, false),array('function', 'url', 'Site/new.html', 13, false),array('modifier', 'date_format', 'Site/new.html', 60, false),)), $this); ?>
<?php
function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_0(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'prevPage'), $_smarty);
}


function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_1(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'new'), $_smarty);
}


function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_2(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'new','page' => $_smarty->_tpl_vars['pager_data']['prevPage']), $_smarty);
}


function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_3(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'prevPage'), $_smarty);
}


function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_4(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'new'), $_smarty);
}


function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_5(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'new','page' => $_smarty->_tpl_vars['pages'][$_smarty->_sections['page']['index']]['number']), $_smarty);
}


function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_6(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'nextPage'), $_smarty);
}


function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_7(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'new','page' => $_smarty->_tpl_vars['pager_data']['nextPage']), $_smarty);
}


function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_8(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'nextPage'), $_smarty);
}


function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_9(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'update_date'), $_smarty);
}


function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_10(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'editsite','id' => $_smarty->_tpl_vars['sites'][$_smarty->_sections['list']['index']]['id']), $_smarty);
}


function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_11(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'edit_or_delete'), $_smarty);
}


function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_12(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'mailadmin','id' => $_smarty->_tpl_vars['sites'][$_smarty->_sections['list']['index']]['id']), $_smarty);
}


function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_13(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'mail_to_admin'), $_smarty);
}


function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_14(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'prevPage'), $_smarty);
}


function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_15(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'new'), $_smarty);
}


function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_16(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'new','page' => $_smarty->_tpl_vars['pager_data']['prevPage']), $_smarty);
}


function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_17(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'prevPage'), $_smarty);
}


function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_18(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'new'), $_smarty);
}


function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_19(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'new','page' => $_smarty->_tpl_vars['pages'][$_smarty->_sections['page']['index']]['number']), $_smarty);
}


function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_20(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'nextPage'), $_smarty);
}


function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_21(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'new','page' => $_smarty->_tpl_vars['pager_data']['nextPage']), $_smarty);
}


function _smarty_tplfunc_66983347496cdbdff87ec8c352460f88_22(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'nextPage'), $_smarty);
}



?>
