<?php /* Smarty version 2.6.18, created on 2012-05-30 15:09:57
         compiled from Admin/pager.html */

$this->_cache_serials['/home/hm1002/GM/gm/link/APP/View/View_c/%%7D^7D7^7D7E27B4%%pager.html.inc'] = 'f907929a204d2e16e416d7c5907beae7';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'url', 'Admin/pager.html', 11, false),array('function', '_t', 'Admin/pager.html', 33, false),)), $this); ?>
<?php
function _smarty_tplfunc_f907929a204d2e16e416d7c5907beae7_0(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => $_smarty->_tpl_vars['controller'],'action' => $_smarty->_tpl_vars['action'],'parent_id' => $_smarty->_tpl_vars['parent']['class_id'],'id' => $_smarty->_tpl_vars['class']['class_id'],'page' => $_smarty->_tpl_vars['pager']['prevPageNumber']), $_smarty);
}


function _smarty_tplfunc_f907929a204d2e16e416d7c5907beae7_1(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => $_smarty->_tpl_vars['controller'],'action' => $_smarty->_tpl_vars['action'],'parent_id' => $_smarty->_tpl_vars['parent']['class_id'],'id' => $_smarty->_tpl_vars['class']['class_id'],'page' => $_smarty->_tpl_vars['Navbar'][$_smarty->_sections['page']['index']]['index']), $_smarty);
}


function _smarty_tplfunc_f907929a204d2e16e416d7c5907beae7_2(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => $_smarty->_tpl_vars['controller'],'action' => $_smarty->_tpl_vars['action'],'parent_id' => $_smarty->_tpl_vars['parent']['class_id'],'id' => $_smarty->_tpl_vars['class']['class_id'],'page' => $_smarty->_tpl_vars['pager']['nextPageNumber']), $_smarty);
}


function _smarty_tplfunc_f907929a204d2e16e416d7c5907beae7_3(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'total'), $_smarty);
}


function _smarty_tplfunc_f907929a204d2e16e416d7c5907beae7_4(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'one'), $_smarty);
}


function _smarty_tplfunc_f907929a204d2e16e416d7c5907beae7_5(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'total'), $_smarty);
}


function _smarty_tplfunc_f907929a204d2e16e416d7c5907beae7_6(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'page'), $_smarty);
}


function _smarty_tplfunc_f907929a204d2e16e416d7c5907beae7_7(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'per_page'), $_smarty);
}


function _smarty_tplfunc_f907929a204d2e16e416d7c5907beae7_8(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'one'), $_smarty);
}



?>
