<?php /* Smarty version 2.6.18, created on 2012-05-30 15:09:49
         compiled from Site/sitesearchresult.html */

$this->_cache_serials['/home/hm1002/GM/gm/link/APP/View/View_c/%%9F^9FC^9FCC73BB%%sitesearchresult.html.inc'] = '935353fa114bfbcd76031791e928528d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', '_t', 'Site/sitesearchresult.html', 8, false),array('function', 'url', 'Site/sitesearchresult.html', 11, false),array('modifier', 'date_format', 'Site/sitesearchresult.html', 56, false),)), $this); ?>
<?php
function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_0(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'prevPage'), $_smarty);
}


function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_1(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'sitesearch'), $_smarty);
}


function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_2(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'sitesearch','page' => $_smarty->_tpl_vars['pager_data']['prevPage']), $_smarty);
}


function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_3(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'prevPage'), $_smarty);
}


function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_4(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'sitesearch'), $_smarty);
}


function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_5(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'sitesearch','page' => $_smarty->_tpl_vars['pages'][$_smarty->_sections['page']['index']]['number']), $_smarty);
}


function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_6(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'nextPage'), $_smarty);
}


function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_7(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'sitesearch','page' => $_smarty->_tpl_vars['pager_data']['nextPage']), $_smarty);
}


function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_8(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'nextPage'), $_smarty);
}


function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_9(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'update_date'), $_smarty);
}


function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_10(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'editsite','id' => $_smarty->_tpl_vars['sites'][$_smarty->_sections['list']['index']]['id']), $_smarty);
}


function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_11(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'edit_or_delete'), $_smarty);
}


function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_12(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'mailadmin','id' => $_smarty->_tpl_vars['sites'][$_smarty->_sections['list']['index']]['id']), $_smarty);
}


function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_13(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'mail_to_admin'), $_smarty);
}


function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_14(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'prevPage'), $_smarty);
}


function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_15(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'sitesearch'), $_smarty);
}


function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_16(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'sitesearch','page' => $_smarty->_tpl_vars['pager_data']['prevPage']), $_smarty);
}


function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_17(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'prevPage'), $_smarty);
}


function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_18(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'sitesearch'), $_smarty);
}


function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_19(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'sitesearch','page' => $_smarty->_tpl_vars['pages'][$_smarty->_sections['page']['index']]['number']), $_smarty);
}


function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_20(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'nextPage'), $_smarty);
}


function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_21(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'sitesearch','page' => $_smarty->_tpl_vars['pager_data']['nextPage']), $_smarty);
}


function _smarty_tplfunc_935353fa114bfbcd76031791e928528d_22(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'nextPage'), $_smarty);
}



?>
