<?php /* Smarty version 2.6.18, created on 2012-05-30 18:10:26
         compiled from Site/sitemap.html */

$this->_cache_serials['/home/hm1002/GM/gm/link/APP/View/View_c/%%9F^9FD^9FD24674%%sitemap.html.inc'] = '93ea5a869b43d8833a64fd34e4be5284';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'url', 'Site/sitemap.html', 76, false),)), $this); ?>
<?php
function _smarty_tplfunc_93ea5a869b43d8833a64fd34e4be5284_0(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'index'), $_smarty);
}


function _smarty_tplfunc_93ea5a869b43d8833a64fd34e4be5284_1(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'regist'), $_smarty);
}


function _smarty_tplfunc_93ea5a869b43d8833a64fd34e4be5284_2(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'renew'), $_smarty);
}


function _smarty_tplfunc_93ea5a869b43d8833a64fd34e4be5284_3(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'new'), $_smarty);
}


function _smarty_tplfunc_93ea5a869b43d8833a64fd34e4be5284_4(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'recommend'), $_smarty);
}


function _smarty_tplfunc_93ea5a869b43d8833a64fd34e4be5284_5(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'sitemap'), $_smarty);
}


function _smarty_tplfunc_93ea5a869b43d8833a64fd34e4be5284_6(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'class','id' => $_smarty->_tpl_vars['class'][$_smarty->_sections['loopClass']['index']]['class_id']), $_smarty);
}


function _smarty_tplfunc_93ea5a869b43d8833a64fd34e4be5284_7(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'class','id' => $_smarty->_tpl_vars['top']['children'][$_smarty->_tpl_vars['index']]['class_id']), $_smarty);
}


function _smarty_tplfunc_93ea5a869b43d8833a64fd34e4be5284_8(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'class','id' => $_smarty->_tpl_vars['top']['children'][$_smarty->_tpl_vars['index2']]['class_id']), $_smarty);
}


function _smarty_tplfunc_93ea5a869b43d8833a64fd34e4be5284_9(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'class','id' => $_smarty->_tpl_vars['top']['children'][$_smarty->_tpl_vars['index3']]['class_id']), $_smarty);
}


function _smarty_tplfunc_93ea5a869b43d8833a64fd34e4be5284_10(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'class','id' => $_smarty->_tpl_vars['top']['children'][$_smarty->_tpl_vars['index4']]['class_id']), $_smarty);
}


function _smarty_tplfunc_93ea5a869b43d8833a64fd34e4be5284_11(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'class','id' => $_smarty->_tpl_vars['top']['children'][$_smarty->_tpl_vars['index5']]['class_id']), $_smarty);
}



?>
