<?php /* Smarty version 2.6.18, created on 2012-05-30 18:14:07
         compiled from Site/header.html */

$this->_cache_serials['/home/hm1002/GM/gm/link/APP/View/View_c/%%A9^A91^A9148E2E%%header.html.inc'] = '0652282735d47eb9343193f5da25fb7d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'url', 'Site/header.html', 78, false),)), $this); ?>
<?php
function _smarty_tplfunc_0652282735d47eb9343193f5da25fb7d_0(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'regist'), $_smarty);
}


function _smarty_tplfunc_0652282735d47eb9343193f5da25fb7d_1(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'renew'), $_smarty);
}


function _smarty_tplfunc_0652282735d47eb9343193f5da25fb7d_2(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'new'), $_smarty);
}


function _smarty_tplfunc_0652282735d47eb9343193f5da25fb7d_3(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'recommend'), $_smarty);
}


function _smarty_tplfunc_0652282735d47eb9343193f5da25fb7d_4(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'sitemap'), $_smarty);
}



?>
