<?php /* Smarty version 2.6.18, created on 2012-05-30 14:59:50
         compiled from Site/siteedit.html */

$this->_cache_serials['/home/hm1002/GM/gm/link/APP/View/View_c/%%AA^AA0^AA0A171D%%siteedit.html.inc'] = 'f83a21819c16bc8f4d4013ba67f05211';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', '_t', 'Site/siteedit.html', 5, false),array('function', 'url', 'Site/siteedit.html', 12, false),)), $this); ?>
<?php
function _smarty_tplfunc_f83a21819c16bc8f4d4013ba67f05211_0(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'site_edit_title'), $_smarty);
}


function _smarty_tplfunc_f83a21819c16bc8f4d4013ba67f05211_1(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'siteupdate'), $_smarty);
}


function _smarty_tplfunc_f83a21819c16bc8f4d4013ba67f05211_2(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'site_update_title'), $_smarty);
}


function _smarty_tplfunc_f83a21819c16bc8f4d4013ba67f05211_3(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'site_id'), $_smarty);
}


function _smarty_tplfunc_f83a21819c16bc8f4d4013ba67f05211_4(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'site_pass'), $_smarty);
}


function _smarty_tplfunc_f83a21819c16bc8f4d4013ba67f05211_5(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'site_update_submit'), $_smarty);
}


function _smarty_tplfunc_f83a21819c16bc8f4d4013ba67f05211_6(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'site_info'), $_smarty);
}


function _smarty_tplfunc_f83a21819c16bc8f4d4013ba67f05211_7(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'site_title'), $_smarty);
}


function _smarty_tplfunc_f83a21819c16bc8f4d4013ba67f05211_8(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'site_url'), $_smarty);
}


function _smarty_tplfunc_f83a21819c16bc8f4d4013ba67f05211_9(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'sitedel'), $_smarty);
}


function _smarty_tplfunc_f83a21819c16bc8f4d4013ba67f05211_10(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'site_del_title'), $_smarty);
}


function _smarty_tplfunc_f83a21819c16bc8f4d4013ba67f05211_11(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'site_id'), $_smarty);
}


function _smarty_tplfunc_f83a21819c16bc8f4d4013ba67f05211_12(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'site_pass'), $_smarty);
}


function _smarty_tplfunc_f83a21819c16bc8f4d4013ba67f05211_13(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'check_del'), $_smarty);
}


function _smarty_tplfunc_f83a21819c16bc8f4d4013ba67f05211_14(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'site_del_submit'), $_smarty);
}



?>
