<?php /* Smarty version 2.6.18, created on 2012-05-30 15:10:13
         compiled from Site/mailtoadmin.html */

$this->_cache_serials['/home/hm1002/GM/gm/link/APP/View/View_c/%%AE^AE2^AE2540B0%%mailtoadmin.html.inc'] = '08dab4b5441709ff889d4a79e88750c6';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'url', 'Site/mailtoadmin.html', 5, false),array('function', '_t', 'Site/mailtoadmin.html', 10, false),)), $this); ?>
<?php
function _smarty_tplfunc_08dab4b5441709ff889d4a79e88750c6_0(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'mailadminsubmit'), $_smarty);
}


function _smarty_tplfunc_08dab4b5441709ff889d4a79e88750c6_1(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'event_type'), $_smarty);
}


function _smarty_tplfunc_08dab4b5441709ff889d4a79e88750c6_2(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'no_link'), $_smarty);
}


function _smarty_tplfunc_08dab4b5441709ff889d4a79e88750c6_3(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'no_link'), $_smarty);
}


function _smarty_tplfunc_08dab4b5441709ff889d4a79e88750c6_4(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'type_move'), $_smarty);
}


function _smarty_tplfunc_08dab4b5441709ff889d4a79e88750c6_5(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'type_move'), $_smarty);
}


function _smarty_tplfunc_08dab4b5441709ff889d4a79e88750c6_6(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'bana_no_link'), $_smarty);
}


function _smarty_tplfunc_08dab4b5441709ff889d4a79e88750c6_7(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'bana_no_link'), $_smarty);
}


function _smarty_tplfunc_08dab4b5441709ff889d4a79e88750c6_8(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'type_ill'), $_smarty);
}


function _smarty_tplfunc_08dab4b5441709ff889d4a79e88750c6_9(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'type_ill'), $_smarty);
}


function _smarty_tplfunc_08dab4b5441709ff889d4a79e88750c6_10(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'type_other'), $_smarty);
}


function _smarty_tplfunc_08dab4b5441709ff889d4a79e88750c6_11(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'type_other'), $_smarty);
}


function _smarty_tplfunc_08dab4b5441709ff889d4a79e88750c6_12(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'comment_title'), $_smarty);
}


function _smarty_tplfunc_08dab4b5441709ff889d4a79e88750c6_13(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'type_fname'), $_smarty);
}


function _smarty_tplfunc_08dab4b5441709ff889d4a79e88750c6_14(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'type_femail'), $_smarty);
}


function _smarty_tplfunc_08dab4b5441709ff889d4a79e88750c6_15(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'send_email'), $_smarty);
}


function _smarty_tplfunc_08dab4b5441709ff889d4a79e88750c6_16(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'com_error'), $_smarty);
}


function _smarty_tplfunc_08dab4b5441709ff889d4a79e88750c6_17(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'femail_error2'), $_smarty);
}


function _smarty_tplfunc_08dab4b5441709ff889d4a79e88750c6_18(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'femail_error3'), $_smarty);
}


function _smarty_tplfunc_08dab4b5441709ff889d4a79e88750c6_19(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'sitelist'), $_smarty);
}



?>
