<?php /* Smarty version 2.6.18, created on 2012-05-30 18:14:07
         compiled from Site/header_search.html */

$this->_cache_serials['/home/hm1002/GM/gm/link/APP/View/View_c/%%EF^EF3^EF3356C6%%header_search.html.inc'] = 'af5b54b12e1b7e8df46b39ea4bd0c400';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', '_t', 'Site/header_search.html', 5, false),array('function', 'url', 'Site/header_search.html', 35, false),)), $this); ?>
<?php
function _smarty_tplfunc_af5b54b12e1b7e8df46b39ea4bd0c400_0(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => $_smarty->_tpl_vars['top_info']['h1']), $_smarty);
}


function _smarty_tplfunc_af5b54b12e1b7e8df46b39ea4bd0c400_1(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => $_smarty->_tpl_vars['top_info']['text']), $_smarty);
}


function _smarty_tplfunc_af5b54b12e1b7e8df46b39ea4bd0c400_2(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => $_smarty->_tpl_vars['top_info']['text']), $_smarty);
}


function _smarty_tplfunc_af5b54b12e1b7e8df46b39ea4bd0c400_3(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'text_out_h1'), $_smarty);
}


function _smarty_tplfunc_af5b54b12e1b7e8df46b39ea4bd0c400_4(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'text_out_p1'), $_smarty);
}


function _smarty_tplfunc_af5b54b12e1b7e8df46b39ea4bd0c400_5(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'text_out_p2'), $_smarty);
}


function _smarty_tplfunc_af5b54b12e1b7e8df46b39ea4bd0c400_6(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'text_out_p3'), $_smarty);
}


function _smarty_tplfunc_af5b54b12e1b7e8df46b39ea4bd0c400_7(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'sitesearch'), $_smarty);
}



?>
