<?php /* Smarty version 2.6.18, created on 2012-05-30 18:14:04
         compiled from Site/indexallclass.html */

$this->_cache_serials['/home/hm1002/GM/gm/link/APP/View/View_c/%%F0^F0D^F0DF6F57%%indexallclass.html.inc'] = 'c100e040aa9055d7ac376adc7b37d52e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'url', 'Site/indexallclass.html', 7, false),)), $this); ?>
<?php
function _smarty_tplfunc_c100e040aa9055d7ac376adc7b37d52e_0(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'class','id' => $_smarty->_tpl_vars['class'][$_smarty->_sections['loopClass']['index']]['class_id']), $_smarty);
}



?>
