<?php /* Smarty version 2.6.18, created on 2012-05-30 17:55:23
         compiled from Site/indexemail.html */

$this->_cache_serials['/home/hm1002/GM/gm/link/APP/View/View_c/%%F5^F5F^F5F4D734%%indexemail.html.inc'] = '5fd1ca37e6c60c3e98f2d21a6463d1eb';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'url', 'Site/indexemail.html', 14, false),)), $this); ?>
<?php
function _smarty_tplfunc_5fd1ca37e6c60c3e98f2d21a6463d1eb_0(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'site','action' => 'class','id' => $_smarty->_tpl_vars['frequentSpecial2'][$_smarty->_sections['loopFrequentSpecial2']['index']]['class']['class_id']), $_smarty);
}



?>
