<?php /* Smarty version 2.6.18, created on 2012-05-30 18:14:07
         compiled from Site/linkcheck.html */

$this->_cache_serials['/home/hm1002/GM/gm/link/APP/View/View_c/%%F7^F72^F72C41C2%%linkcheck.html.inc'] = '24f5e87a46cb2ffb0f0b596e73035987';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', '_t', 'Site/linkcheck.html', 5, false),array('function', 'url', 'Site/linkcheck.html', 52, false),)), $this); ?>
<?php
function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_0(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'seoplink_submit_title'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_1(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'seoplink_attention'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_2(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'attention_item1_title'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_3(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'attention_item1_content'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_4(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'link_tag'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_5(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'attention_item1_warning'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_6(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'attention_item2_title'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_7(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'attention_item2_content'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_8(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'attention_item3_title'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_9(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'attention_item4_title1'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_10(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'attention_item4_title2'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_11(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'content_attention1'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_12(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'content_attention2'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_13(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'Site','action' => 'linkcheck_submit'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_14(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'Site','action' => 'checkurl'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_15(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'seoplink_fname'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_16(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'require_symbol'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_17(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'fname_attention'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_18(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'seoplink_femail'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_19(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'require_symbol'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_20(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'femail_attention'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_21(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'seoplink_fpass'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_22(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'require_symbol'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_23(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'fpass_attention'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_24(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'fpass2_explanation'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_25(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'seoplink_site_name'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_26(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'require_symbol'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_27(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'name_attention'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_28(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'seoplink_site_url'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_29(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'require_symbol'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_30(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'url_attention'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_31(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'seoplink_site_comment'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_32(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'require_symbol'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_33(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'comment_attention'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_34(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'seoplink_site_category'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_35(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'require_symbol'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_36(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'category_attention'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_37(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'seoplink_site_linkpage_url'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_38(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'require_symbol'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_39(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'linkpage_url_attention'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_40(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'Admin','action' => 'imgCode'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_41(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'seoplink_site_submit'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_42(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'seoplink_site_reset'), $_smarty);
}


function _smarty_tplfunc_24f5e87a46cb2ffb0f0b596e73035987_43(&$_smarty)
{
echo $_smarty->_plugins['function']['_t'][0][0]->_pi_func_t(array('key' => 'site_preview'), $_smarty);
}



?>
